inherit_from:
  - .rubocop_airbnb.yml
#ここにはrubocopで検証したくないファイルやフォルダを指定
AllCops:
  Exclude:
      - 'db/**/*'
      - 'bin/*'
      - 'config/environments/*'
      - 'config/application.rb'
      - 'config/initializers/*'
      - 'config/spring.rb'
      - 'lib/tasks/*'
      - 'vendor/**/*'
      - 'config/routes.rb'
      - 'spec/spec_helper.rb'